# Generated by Django 4.1 on 2022-09-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('datanasc', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('formafisica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='VidapubliArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='privado.time')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.usuario')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='privado.time')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoArbitro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='Conflito',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=260)),
                ('errotecnico', models.BooleanField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.arbitro')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.partida')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.time')),
            ],
        ),
        migrations.AddField(
            model_name='arbitro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.cidade'),
        ),
    ]
